export default function Home() {
  return (
    <div>
      <head>
        <title> Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <h1>Hello World!</h1>
    </div>
  );
}
