import Head from "next/head";
import Sidebar from "../components/Sidebar";

export default function Home() {
  return (
    <div>
      <Head>
        <title> Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        {/* Side Bar */}
        <Sidebar />

        {/* Feed */}

        {/* Widgets */}

        {/* Model */}
      </main>
    </div>
  );
}
